# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 8.2.3
  buildConfiguration: 'Release'
  slackUrl1 : 'https://hooks.slack.com/services/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'
  teams : 'https://uitacma.webhook.office.com/webhookb2/86c9f44a-de61-4a51-8815-f11c1f02872b@7c31a0e5-7974-4f01-831a-88f007bb9711/IncomingWebhook/ad913b65800f414a8db5cbf73d10e55a/7dff2da0-1ce3-4257-9a77-a91735c519ca'
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
- job: GIGD_TP_CI_CD
  steps:
  - script: |
      sudo update-alternatives --set php /usr/bin/php$(phpVersion)
      sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
      sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
      sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
      sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
      php -version
    displayName: 'Use PHP version $(phpVersion)'

  - script: composer install --no-interaction --prefer-dist
    displayName: 'composer install'


  - script: |
     php --version
     composer install --no-interaction --prefer-dist
     php index.php
    displayName: 'Build and run PHP app'
    timeoutInMinutes: 1

  - script: |
      composer install
    displayName: 'Install dependencies'
  
  - script: |
      chmod +x vendor/bin/phpcs
          vendor/bin/phpcs --standard=PSR2 --warning-severity=0 index.php
    displayName: 'Run PHP CodeSniffer'

  - script: |
      chmod +x vendor/bin/phpunit
      vendor/bin/phpunit tests
    displayName: 'Run PHPUnit tests'

  - script: |
     curl -H "Content-Type: application/json" -d '{"title": "Pipeline azure CI/CD", "text": "Le pipeline a ete execute avec succes"}' $(teams)
    displayName: 'Send message to Teams'

  - script: |
     curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, world!"}' $SLACK_WEBHOOK_URL
    displayName: 'Send Slack message'

