trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    php -v
    composer install
    vendor/bin/phpunit tests/
  displayName: 'PHPUnit Tests'
  
- task: PHPUnit@2
  inputs:
    testRunner: 'PHPUnit'
    testResultsFormat: 'JUnit'
    phpunitConfig: '/path/to/phpunit.xml'
    workingDirectory: '$(Build.SourcesDirectory)/path/to/tests'